### ISSUE TITLE
rbenv throws error when running bundler during rails 4.2.0 new app creation process

### ISSUE THREAD

**Issue by mankind** [sstephenson/rbenv#669]
I am on Ubuntu 13.10 using **rbenv  version 2.1.2**,  **ruby  version 2.1.2p95** and rubygems is the latest version **2.4.5** with bundler versions is  **1.7.9**. I am trying to upgrade to rails 4.2.0. After installing **rails 4.2.0**, creating a new app with the **rails new** command throws an error when trying to run bundle install. If I uninstall **rails 4.2.0** and leave just **rails 4.1.6** and create a new app, this time bundler will run without error. Note also that with **rails 4.2.0** if I skip bundler with **rails new my-app-name --skip-bundle**, the error goes away but if I don't  **--skip-bundle** the error shown below is thrown:

     /home/biggy/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- bundler (LoadError)
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/generators/app_base.rb:319:in `bundle_command'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/generators/app_base.rb:335:in `run_bundle'
	from (eval):1:in `run_bundle'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/biggy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/bin/rails:9:in `<top (required)>'
	from /home/biggy/.rbenv/versions/2.1.2/bin/rails:23:in `load'
	from /home/biggy/.rbenv/versions/2.1.2/bin/rails:23:in `<main>'

**Comment by mislav** [comment]
@mankind Is this issue still present for you? I haven't heard of anything similar. I'd like to close this if we can't find conclusive evidence that this is a bug of rbenv.

**Comment by mankind** [comment]
The problem is still there but it can be closed.

Many thanks.

**Comment by kangkyu** [comment]
I met the same error - and it worked after uninstall all the gems including bundler, and follow this troubleshoot instruction (https://github.com/bundler/bundler/issues/3317) - in my case `ruby 2.1.6 rails 4.0.13 gem 2.5.0 bundler 1.10.5 rbenv 0.4.0`

**Comment by hassanazimi** [comment]
Go to /usr/local/lib and delete the ruby folder. then in command line type gem update and after that rails new will work but do not try to run gem update --system. I think the gem isn't compatible yet.

**Comment by ZzAntares** [comment]
I'm also experiencing this problem, this is the steps that you could follow to confirm this (I'm using latest rbenv and ruby 2.2.3):

```sh
$ gem install rails
$ rails new my_app  # runs fine
$ rm -rf my_app
$ rails new my_app  # throws error
```

However as @mankind says doing this will work without any issues

```
$ rails new my_app --skip-bundle
$ cd my_app
$ bundle install
```

```log
.
.
.
create  test/test_helper.rb
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
         run  bundle install
/Users/antares/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- bundler (LoadError)
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators/app_base.rb:319:in `bundle_command'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators/app_base.rb:335:in `run_bundle'
	from (eval):1:in `run_bundle'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/cli.rb:14:in `<top (required)>'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/antares/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/bin/rails:9:in `<top (required)>'
	from /Users/antares/.rbenv/versions/2.2.3/bin/rails:23:in `load'
	from /Users/antares/.rbenv/versions/2.2.3/bin/rails:23:in `<main>'
```

**Comment by abepark01** [comment]
I pulled latest for rails 4.2.5, rbenv and ruby-build, and am getting the same error @ZzAntares .
```
gem install rails
rbenv rehash
rails new myapp
```

```
/home/abe/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- bundler (LoadError)
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/generators/app_base.rb:330:in `bundle_command'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/generators/app_base.rb:346:in `run_bundle'
	from (eval):1:in `run_bundle'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/abe/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/bin/rails:9:in `<top (required)>'
	from /home/abe/.rbenv/versions/2.2.3/bin/rails:23:in `load'
	from /home/abe/.rbenv/versions/2.2.3/bin/rails:23:in `<main>'
```

**Comment by fladson** [comment]
Just to say that I'm getting the same error as above.

Running ruby 2.2.3 and rails 4.2.5 as well.

**Comment by abepark01** [comment]
It looks like the issue is with RubyGems 2.5.0; the rails new command works in RubyGems 2.4.5.1 against rails 4.2.5 and ruby 2.2.2/2.2.3.

It does look like the issue happens on the latest version of RubyGems
The following works:
```
gem --version
# 2.4.5.1
rails new myapp
```
The error I posted above occurs when I update RubyGem
```
gem update --system
get --version
# 2.5.0
rails new myapp
````
**Error Output**
```
/Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- bundler (LoadError)
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/generators/app_base.rb:330:in `bundle_command'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/generators/app_base.rb:346:in `run_bundle'
	from (eval):1:in `run_bundle'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/cli.rb:14:in `<top (required)>'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/abe.park/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/bin/rails:9:in `<top (required)>'
	from /Users/abe.park/.rbenv/versions/2.2.3/bin/rails:23:in `load'
	from /Users/abe.park/.rbenv/versions/2.2.3/bin/rails:23:in `<main>'
```

**Comment by everestlab** [comment]
Yes i am also getting this error.

Ruby version 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
Rails 2.5.0

**Comment by brchiu** [comment]
I also get this error... sigh..

$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-cygwin]
$ gem --version
2.5.0
$ rails --version
Rails 4.2.5

**Comment by ZzAntares** [comment]
is there any solution to this @mislav ?

Thanks

**Comment by hsbt** [comment]
It's not rbenv issue. Please see https://github.com/rubygems/rubygems/issues/1395

**Comment by nasirmaan** [comment]
I am getting same error.
Was someone able to find the solution?

**Comment by abepark01** [comment]
It looks like rubygems 2.5.1 fixes this issue; the error goes away after doing gem update --system

The issue existed in gem 2.5.0.

Thanks!

https://github.com/rubygems/rubygems/tree/v2.5.1

**Comment by CharlieIGG** [comment]
I had this problem with RubyGems 2.5.0 and can confirm that the newest 2.5.1 fixes this issue. ;)

**Comment by jwoertink** [comment]
I'm running in to this issue with gem `2.5.1` 😢 

```text
[web@server 20160516234406]$ which bundle
~/.rbenv/shims/bundle
[web@server 20160516234406]$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
[web@server 20160516234406]$ gem -v
2.5.1
[web@server 20160516234406]$ rbenv -v
rbenv 1.0.0
[web@server 20160516234406]$ rbenv exec bundle install
/home/web/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /home/web/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/web/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/exe/bundle:7:in `<top (required)>'
	from /home/web/.rbenv/versions/2.3.0/bin/bundle:23:in `load'
	from /home/web/.rbenv/versions/2.3.0/bin/bundle:23:in `<main>'
[web@server 20160516234406]$ bundle install
/home/web/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /home/web/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/web/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/exe/bundle:7:in `<top (required)>'
	from /home/web/.rbenv/versions/2.3.0/bin/bundle:23:in `load'
	from /home/web/.rbenv/versions/2.3.0/bin/bundle:23:in `<main>'
[web@server 20160516234406]$ gem install bundler
Successfully installed bundler-1.12.4
1 gem installed
[web@server 20160516234406]$ rbenv rehash
[web@server 20160516234406]$ rbenv shims
/home/web/.rbenv/shims/bundle
/home/web/.rbenv/shims/bundler
/home/web/.rbenv/shims/erb
/home/web/.rbenv/shims/erubis
/home/web/.rbenv/shims/gem
/home/web/.rbenv/shims/irb
/home/web/.rbenv/shims/nokogiri
/home/web/.rbenv/shims/rackup
/home/web/.rbenv/shims/rails
/home/web/.rbenv/shims/rake
/home/web/.rbenv/shims/rdoc
/home/web/.rbenv/shims/ri
/home/web/.rbenv/shims/ruby
/home/web/.rbenv/shims/sprockets
/home/web/.rbenv/shims/thor
[web@server 20160516234406]$ which bundle
~/.rbenv/shims/bundle
[web@server 20160516234406]$ bundle install
/home/web/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /home/web/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/web/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/exe/bundle:7:in `<top (required)>'
	from /home/web/.rbenv/versions/2.3.0/bin/bundle:23:in `load'
	from /home/web/.rbenv/versions/2.3.0/bin/bundle:23:in `<main>'

```
