### ISSUE TITLE
Mac OS X 10.9.5, Cant install ruby 2.2.1

### ISSUE THREAD

**Issue by rizalmuthi** [sstephenson/rbenv#708]
``` 
rbenv install 2.2.1
Downloading ruby-2.2.1.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/5a4de38068eca8919cb087d338c0c2e3d72c9382c804fb27ab746e6c7819ab28
Installing ruby-2.2.1...

BUILD FAILED (OS X 10.9.5 using ruby-build 20150303)

Inspect or clean up the working tree at /var/folders/nh/x8vjwnc17_19rfsslcy5g7xh0000gn/T/ruby-build.20150317161430.33004
Results logged to /var/folders/nh/x8vjwnc17_19rfsslcy5g7xh0000gn/T/ruby-build.20150317161430.33004.log


Last 10 log lines:
	from /private/var/folders/nh/x8vjwnc17_19rfsslcy5g7xh0000gn/T/ruby-build.20150317161430.33004/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/var/folders/nh/x8vjwnc17_19rfsslcy5g7xh0000gn/T/ruby-build.20150317161430.33004/ruby-2.2.1/lib/rubygems.rb:556:in `install'
	from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:721:in `each'
	from ./tool/rbinstall.rb:721:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-all] Error 1
```

Any idea whats wrong? I have tried to google it, could not find what is the problem

**Comment by rizalmuthi** [comment]
I have tried to install other version of ruby, it does not work too
Seem my environment problem. Any idea how to trouble shoot this?
Really appreciate it.

Thanks

**Comment by syndbg** [comment]
See the Mac OSX section, it might help you https://github.com/sstephenson/ruby-build/wiki

**Comment by mislav** [comment]
@rizalmuthi If you open the full log file indicated at the "Results logged to" line, the full error message might give you and us better indication and what went wrong. In the console you only see 10 last lines, which is not enough because there was a big stack trace which we only see the last bit of.

**Comment by velvia** [comment]
Here are the last 20 lines or so of mine.  Too bad it seems to be different.
```
/var/folders/3q/8rxj4ny1463b803k_l99yllw0000gn/T/ruby-build.20150326142340.24412/yaml-0.1.6 /var/folders/3q/8rxj4ny1463b803k_l99yllw0000gn/T/ruby-build.20150326142340.24412 ~
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
...skipping...
        CPPFLAGS = -I/usr/local/Cellar/rbenv/0.4.0/versions/2.1.0/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/x86_64-darwin13.0 -I./include -I.
        DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -fstack-protector -Wl,-u,_objc_msgSend -Wl,-pie -framework CoreFoundation
        SOLIBS =
compiling main.c
compiling dmydln.c
compiling miniinit.c
Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
compiling miniprelude.c
translating probes probes.d
compiling bignum.c
compiling class.c
compiling compar.c
error: unable to open output file '/dev/fd/9': ''
1 error generated.
dtrace: failed to compile script probes.d: Preprocessor failed to process input program
make: *** [probes.h] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by rizalmuthi** [comment]
Hi guys, thanks for the replied, I have no idea what I did (I tried many things randomly after google and looking at stackoverflow) now its working fine... Shall I close this?
Thanks

**Comment by velvia** [comment]
Btw I found the solution to my problem.  Chmod -s /usr/sbin/dtrace

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by Yago580** [comment]
@velvia Thank you so much!!! I was having the same problem and that fixed it.

**Comment by JustinWinthers** [comment]
I was having similar problems but when I installed via RVM it worked just fine.

http://foffer.dk/install-ruby-on-os-x-10-10-yosemite-using-rvm/

**Comment by mislav** [comment]
Further reports of build problems should go to https://github.com/sstephenson/ruby-build/issues tracker instead. Thanks!
