### ISSUE TITLE
El Capitan with Ruby ruby 1.9.3p551 openssl LoadError 

### ISSUE THREAD

**Issue by mech** [sstephenson/rbenv#805]
Hi, I have a branch new El Capitan fresh install. Using `rbenv install 1.9.3p551` and doing a `gem install bundler`, but having this `LoadError`

```
/Users/[snip]/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/remote_fetcher.rb:329:in
    `rescue in connection_for': cannot load such file -- openssl (LoadError)
```

I am wondering if it is because El Capitan cannot support Ruby 1.9.3 like it is 100% deprecated.

**Comment by mislav** [comment]
Hi, please [try the latest release](https://github.com/sstephenson/ruby-build/releases/tag/v20151024)! This should have been fixed with #808. Thanks

**Comment by asadakbar** [comment]
Hi, I seem to still be having this issue. I uninstalled all versions of ruby-build through homebrew, and rbenv, and reinstalled both of them. I am still running into this issue [Issue 576](https://github.com/rbenv/rbenv/issues/576), tried `gem install bundler` and am hitting the same error above as mech.

**Comment by mislav** [comment]
@asadakbar Sorry you're having trouble, but you haven't given us any info, like for instance which Ruby version are you trying this with, or is it possible that you have double installs of ruby-build, perhaps one as a plugin in `~/.rbenv/plugins/ruby-build` in addition to being installed with Homebrew? (That's a common problem that people have.) Have you tried [`rbenv-doctor`](https://github.com/rbenv/rbenv-installer#rbenv-doctor)?

**Comment by thefonso** [comment]
This still seems to be a problem. 

```
$ gem install bundler
/Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/remote_fetcher.rb:329:in `rescue in connection_for': cannot load such file -- openssl (LoadError)
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/remote_fetcher.rb:307:in `connection_for'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/remote_fetcher.rb:402:in `request'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/remote_fetcher.rb:205:in `fetch_http'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/remote_fetcher.rb:238:in `fetch_path'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:260:in `load_specs'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:231:in `block in list'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:227:in `each'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:227:in `list'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:150:in `find_matching_with_errors'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:89:in `fetch_with_errors'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/dependency_installer.rb:110:in `find_gems_with_sources'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/dependency_installer.rb:228:in `find_spec_by_name_and_version'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/dependency_installer.rb:259:in `install'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/commands/install_command.rb:121:in `block in execute'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/commands/install_command.rb:115:in `each'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/commands/install_command.rb:115:in `execute'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/command.rb:278:in `invoke'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/command_manager.rb:147:in `process_args'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/command_manager.rb:117:in `run'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/gem_runner.rb:65:in `run'
	from /Users/aleph/.rbenv/versions/1.9.3-p547/bin/gem:21:in `<main>'
```
rbenv-doctor output

```
$ curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20200224)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```
